In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/train.csv')

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [ ]:
print("\n--- Ringkasan Dataset ---")

df.info()

--- Ringkasan Dataset ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
# Menampilkan baris yang kolom 'Postal Code'-nya kosong (NaN)
df_kosong = df[df['Postal Code'].isnull()]
display(df_kosong[['Order ID', 'Customer Name', 'City', 'State', 'Postal Code']])

            Order ID     Customer Name        City    State  Postal Code
2234  CA-2018-104066      Quincy Jones  Burlington  Vermont          NaN
5274  CA-2016-162887  Stewart Visinsky  Burlington  Vermont          NaN
8798  US-2017-150140   Valerie Mitchum  Burlington  Vermont          NaN
9146  US-2017-165505  Claudia Bergmann  Burlington  Vermont          NaN
9147  US-2017-165505  Claudia Bergmann  Burlington  Vermont          NaN
9148  US-2017-165505  Claudia Bergmann  Burlington  Vermont          NaN
9386  US-2018-127292     Raymond Messe  Burlington  Vermont          NaN
9387  US-2018-127292     Raymond Messe  Burlington  Vermont          NaN
9388  US-2018-127292     Raymond Messe  Burlington  Vermont          NaN
9389  US-2018-127292     Raymond Messe  Burlington  Vermont          NaN
9741  CA-2016-117086      Quincy Jones  Burlington  Vermont          NaN

In [ ]:
# Mengisi (Fill) nilai kosong pada Postal Code dengan angka 5401
df['Postal Code'] = df['Postal Code'].fillna(5401)

# Mengubah tipe data Postal Code dari float (desimal) menjadi string (teks)
# Karena kodepos bukan angka untuk dijumlahkan/dikurangi
df['Postal Code'] = df['Postal Code'].astype(int).astype(str)

In [ ]:
# Mengubah format data dan Menambahkan dayfirst=True agar Pandas tahu formatnya Tanggal/Bulan/Tahun
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

In [ ]:
print("\n--- Ringkasan Dataset ---")

df.info()

--- Ringkasan Dataset ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9800 non-null   object
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(1), int64(1), object(14)
memory usage: 1.3+ MB

In [ ]:
# Menyimpan dataset yang sudah bersih menjadi file CSV baru
df.to_csv('Superstore_Cleaned.csv', index=False)
print("Data bersih berhasil disimpan sebagai 'Superstore_Cleaned.csv'!")

Data bersih berhasil disimpan sebagai 'Superstore_Cleaned.csv'!